AWSTemplateFormatVersion: "2010-09-09"
Description: CloudFront distribution for help.gutools.co.uk

Parameters:
  OriginBucketSite:
    Description: The endpoint for the S3 bucket static hosted site
    Type: String
  SSLCertificate:
    Description: ACM certificate for CloudFront
    Type: String
  S3BucketName:
    Description: Name of the S3 Bucket
    Type: String
    Default: 'editorial-tools-help'
  OriginAccessId:
    Description: Id of OriginAccessIdentity user
    Type: String
  CNAME:
    Description: gutools domain CNAME
    Type: String
    Default: help.gutools.co.uk

Resources:
  distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
        - DomainName: !Ref 'OriginBucketSite'
          Id: help
          S3OriginConfig:
            OriginAccessIdentity: !Sub 'origin-access-identity/cloudfront/${OriginAccessId}'
        Enabled: 'true'
        Aliases:
        - !Ref 'CNAME'
        DefaultCacheBehavior:
          AllowedMethods:
          - GET
          - HEAD
          TargetOriginId: help
          ForwardedValues:
            QueryString: 'false'
            Cookies:
              Forward: none
          ViewerProtocolPolicy: redirect-to-https
        ViewerCertificate:
          AcmCertificateArn: !Ref 'SSLCertificate'
          MinimumProtocolVersion: TLSv1
          SslSupportMethod: sni-only
        DefaultRootObject: index.html
        HttpVersion: http2
